---
name: Bug Report
about: 报告一个问题帮助我们改进
title: '[Bug] '
labels: bug
assignees: ''
---

## 🐛 Bug 描述

简要描述遇到的问题。

## 📍 复现步骤

1. 进入 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 看到错误

## ✅ 预期行为

描述你期望应该发生什么。

## ❌ 实际行为

描述实际发生了什么。

## 📸 截图

如果适用，添加截图来解释问题。

## 🖥️ 环境信息

- **OS**: [例如 macOS 14.0, Windows 11, Ubuntu 22.04]
- **应用版本**: [例如 v0.1.2]
- **架构**: [例如 x64, ARM64]

## 📋 附加信息

添加其他有助于解释问题的信息。
