---
name: Feature Request
about: 为这个项目提出一个想法
title: '[Feature] '
labels: enhancement
assignees: ''
---

## 🚀 功能描述

简要描述你想要的功能。

## 💡 用例

描述这个功能解决了什么问题，或者为什么需要这个功能。

## 🔄 替代方案

描述你考虑过的替代解决方案或功能。

## 📐 建议的实现方案

如果你有想法，可以描述一下你建议如何实现这个功能。

## 🎨 附加信息

添加截图、示例或其他有助于说明这个功能的信息。
